# Generated by Django 3.1 on 2020-08-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('cost_price', models.CharField(max_length=50)),
                ('selling_price', models.CharField(max_length=50)),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.CharField(max_length=50)),
                ('product', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
    ]
