# Generated by Django 3.1 on 2020-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200820_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
